name: Build web page

on:
  pull_request:
    paths:
      - ./**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Build page
      run: npm run build