name: Build web page

on: [push, pull_request]

jobs:
  build_deploy:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install
    - name: Build page
      run: npm run build
    - uses: actions/upload-pages-artifact@v0
      with:
        path: ./dist
        retention-days: 1
    - uses: actions/deploy-pages@v1
      permissions:
        packages: write
